### ISSUE TITLE
script not shutting down all processes when exiting the script

### ISSUE THREAD

**Issue by eskoONE** [Specnr/MultiResetWall#112]
https://i.imgur.com/M7x2zFx.png

i have a bunch of processes left over whenever i quit the script. in the screenshot u can see the processes left over after starting and quitting the script 3 times. while this isnt a problem per se, it would be nice if this didnt happen.

**Comment by Specnr** [comment]
this issue has been solved for a while, make sure youre on the latest macro and on the correct ahk version

**Comment by eskoONE** [comment]
this is happening with 1.1.1, thats why i reported it.
