### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by ImplicitlyGus** [Specnr/MultiResetWall#20]
Hi Dearest Specnr,

I'm not familiar with Github, but I clicked on the questions thing in Pull Requests and it led me here so I suppose I shall ask a question. Is there a way to check if 
1. Hitboxes are on
2. Chunk borders are on
3. Which F5 mode you are on

Through any sort of macro. Asking cause I might make a cool pull request soon 👀 

**Thank you, Specnr.**
_- :gus:_

Postscript: Oh and by the way specnr. Which AHK file and which lines in that file are the exact lines that make you reset the instance you are selected on (not like resetting it on Wall scene) and do settings and stuff like that (FOR THE VERSION WITHOUT WP) thanks specnr!

Postscript 2: (LAST QUESTION SORRY SPECNR MAN!) Will you add Auto-Freezing to a non-world preview version pretty please specnr i want the performance 🥺

**Comment by Specnr** [comment]
1. no
2. no
3. no

postscript: look at the ExitWorld function
postscript 2: that doesnt make sense, how can you freeze the preview when not using world preview. if you mean instance freezing, it isnt worth it for 99% of people, just use dynamic fps
