### ISSUE TITLE
Reset.ahk (i think) fails to reset

### ISSUE THREAD

**Issue by MuhammadSban** [Specnr/MultiResetWall#9]
When I use the wall, almost everything works, however it only resets once before spitting out the error message below. 
![Log](https://user-images.githubusercontent.com/69867570/143192604-dd93c2e5-54fd-48f6-a28d-6d89ef4eb2f4.PNG)

Any advice on this would be much appreciated as I am not that code-brained. Thank you!

**Comment by SpeedNintendo** [comment]
I'd DM specnr on discord.

**Comment by Specnr** [comment]
read the instructions, as of now you cant have spaces in folder structure
